name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${bukkit.pluginyml.author}
main: ${bukkit.pluginyml.main}

depend: [ProtocolLib]
softdepend: [FlickeringPumkins] #For better and easier checking whether the plugin is there

commands:
  flickeringpumpkinslite:
    description: Handle Flickering pumpkins
    aliases: [fpl, flickerpumpkin, flickerpumpkins, flickeringpumpkin, flickeringpumpkins, pumpkins, fp]
    permission: flickeringpumpkinslite.command.use
    permission-message: "§6${project.name} §7- §6v${project.version} §7- §6by ${bukkit.pluginyml.author}"
    usage: "/<command> help"
